"""empty message

Revision ID: 126d47f1e280
Revises: 854186bcf477
Create Date: 2022-04-30 13:32:30.246323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '126d47f1e280'
down_revision = '854186bcf477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'public_address')
    op.drop_column('user', 'location')
    op.drop_column('user', 'birthday_date')
    op.drop_column('user', 'login_count')
    op.drop_column('user', 'instagram')
    op.drop_column('user', 'header_image')
    op.drop_column('user', 'nonce')
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'image_highlights')
    op.drop_column('user', 'last_login_ip')
    op.drop_column('user', 'bio')
    op.drop_column('user', 'apple')
    op.drop_column('user', 'profile_image')
    op.drop_column('user', 'current_login_ip')
    op.drop_column('user', 'interests')
    op.drop_column('user', 'current_login_at')
    op.drop_column('user', 'verified_at')
    op.drop_column('user', 'facebook')
    op.drop_column('user', 'configuration')
    op.add_column('variation', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.drop_column('variation', 'engine')
    op.drop_column('variation', 'max_speed')
    op.drop_column('variation', 'power')
    op.drop_column('variation', 'valves')
    op.drop_column('variation', 'price')
    op.drop_column('variation', 'weight')
    op.drop_column('variation', 'refiregeration')
    op.drop_column('variation', 'cubic')
    op.drop_column('variation', 'fuel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variation', sa.Column('fuel', sa.VARCHAR(), nullable=True))
    op.add_column('variation', sa.Column('cubic', sa.VARCHAR(), nullable=True))
    op.add_column('variation', sa.Column('refiregeration', sa.VARCHAR(), nullable=True))
    op.add_column('variation', sa.Column('weight', sa.VARCHAR(), nullable=True))
    op.add_column('variation', sa.Column('price', sa.FLOAT(), nullable=True))
    op.add_column('variation', sa.Column('valves', sa.VARCHAR(), nullable=True))
    op.add_column('variation', sa.Column('power', sa.VARCHAR(), nullable=True))
    op.add_column('variation', sa.Column('max_speed', sa.VARCHAR(), nullable=True))
    op.add_column('variation', sa.Column('engine', sa.VARCHAR(), nullable=True))
    op.drop_column('variation', 'extra_data')
    op.add_column('user', sa.Column('configuration', sqlite.JSON(), nullable=True))
    op.add_column('user', sa.Column('facebook', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('verified_at', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('current_login_at', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('interests', sa.VARCHAR(), nullable=True))
    op.add_column('user', sa.Column('current_login_ip', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('profile_image', sa.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('apple', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('bio', sa.VARCHAR(), nullable=True))
    op.add_column('user', sa.Column('last_login_ip', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('image_highlights', sa.VARCHAR(), nullable=True))
    op.add_column('user', sa.Column('last_login_at', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('nonce', sa.VARCHAR(), nullable=True))
    op.add_column('user', sa.Column('header_image', sa.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('instagram', sa.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('login_count', sa.INTEGER(), nullable=True))
    op.add_column('user', sa.Column('birthday_date', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('location', sa.VARCHAR(), nullable=True))
    op.add_column('user', sa.Column('public_address', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
