"""empty message

Revision ID: b6956dc56623
Revises: 126d47f1e280
Create Date: 2022-04-30 16:18:13.855460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6956dc56623'
down_revision = '126d47f1e280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variation', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variation', 'price')
    # ### end Alembic commands ###
