"""empty message

Revision ID: b7654c0e872f
Revises: 
Create Date: 2022-04-30 02:10:54.831859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7654c0e872f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variation',
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('model_year', sa.Integer(), nullable=True),
    sa.Column('cubic', sa.String(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('fuel', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('max_speed', sa.String(), nullable=True),
    sa.Column('power', sa.String(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('refiregeration', sa.String(), nullable=True),
    sa.Column('valves', sa.String(), nullable=True),
    sa.Column('fetch_state', sa.String(), nullable=True),
    sa.Column('fetch_date', sa.DateTime(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variation')
    op.drop_table('brand')
    # ### end Alembic commands ###
